pool:
  vmImage: 'windows-latest'

steps:
- task: Cache@2
  displayName: 'Grab cache folder'
  inputs:
    key: 'cachedir-v4 | "$(Agent.OS)"'
    path: cache

- task: CmdLine@2
  displayName: 'Prepare git config'
  inputs:
    script: |
      git config --global core.autocrlf false
      git config --global core.whitespace cr-at-eol

- task: PowerShell@2
  displayName: 'Run build.ps1'
  inputs:
    filePath: 'build.ps1'
    arguments: '-Redist'

- task: ArchiveFiles@2
  displayName: 'Create ahornvhd.7z'
  inputs:
    rootFolderOrFile: 'out'
    includeRootFolder: false
    archiveType: '7z'
    sevenZipCompression: 'ultra'
    archiveFile: '$(Build.ArtifactStagingDirectory)/ahornvhd.7z'
    replaceExistingArchive: true
    verbose: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish main artifact'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/'
    artifactName: 'main'
    publishLocation: 'Container'

- task: CopyFilesOverSSH@0
  displayName: 'Upload to VPS'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    sshEndpoint: 'ahornvhd@vps.0x0ade.ga'
    sourceFolder: '$(Build.ArtifactStagingDirectory)/'
    contents: '**'
    targetFolder: '/home/ahornvhd/public/'
    readyTimeout: '20000'
