pool:
  vmImage: 'windows-latest'

steps:
- task: Cache@2
  displayName: 'Grab cache folder'
  inputs:
    key: 'cachedir-v1 | "$(Agent.OS)"'
    path: cache

- task: PowerShell@2
  displayName: 'Run build.ps1'
  inputs:
    filePath: 'build.ps1'
    arguments: '-Redist'

- task: CopyFiles@2
  displayName: 'Pack main artifact'
  inputs:
    sourceFolder: '$(Agent.BuildDirectory)'
    contents: '**/out/**/*'
    targetFolder: '$(Build.ArtifactStagingDirectory)/'
    cleanTargetFolder: true
    overWrite: true
    flattenFolders: true

- task: PublishBuildArtifacts@1
  condition: succeeded()
  displayName: 'Publish main artifact'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/'
    artifactName: 'main'
    publishLocation: 'Container'
